# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_subgraphs_as_molecules": "00_core.ipynb",
         "MOF": "00_core.ipynb",
         "SBU": "01_sbu.ipynb",
         "Node": "01_sbu.ipynb",
         "Linker": "01_sbu.ipynb",
         "get_binding_indices": "01_sbu.ipynb"}

modules = ["core.py",
           "sbu.py"]

doc_url = "https://kjappelbaum.github.io/moffragmentor/"

git_url = "https://github.com/kjappelbaum/moffragmentor/tree/master/"

def custom_doc_links(name): return None
