name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    strategy:
      matrix:
        python-version: ["3.8"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          conda install jupyterlab=3 nglview   openbabel rdkit ase click -y
          pip install "pymatgen>=2021.1,<2022"
          pip install git+https://github.com/skearnes/rdkit-utils.git

          pip install -e .
          pip install pytest pytest-cov
      - name: Run pre-commit
        run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
